services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: data-claims-reporting-service-local-postgres
      SPRING_PROFILES_ACTIVE: local
      LOCALSTACK_HOST: localstack
  postgres:
    image: postgres:17
    container_name: data-claims-reporting-service-local-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laa_claims_reporting_service_dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  #  local AWS cloud stack for dev
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - LOCALSTACK_INIT_SCRIPTS=/etc/localstack/init/ready.d
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack-init:/etc/localstack/init/ready.d"
volumes:
  postgres-data: