spring:
  flyway:
    locations:
      - classpath:db/migration/schema
      - classpath:db/testdata

# Normally these come from Kubernetes hence the formatting difference
S3_REPORT_STORE: "test-bucket"
AWS_REGION: "eu-west-1"